### ISSUE TITLE
Error running Main.py

### ISSUE THREAD

**Issue by gspitman** [BSFEMA/RPi_WS2812#4]
I'm getting the following when entering "sudo python main.py":

`Traceback (most recent call last):
  File "main.py", line 13, in <module>
    strip.begin()
  File "/home/pi/rpi_ws281x-master/python/examples/RPi_WS2812/neopixel.py", line 106, in begin
    raise RuntimeError('ws2811_init failed with code {0} ({1})'.format(resp, message))
RuntimeError: ws2811_init failed with code -3 (Hardware revision is not supported)
`

**Comment by sergge1** [comment]
the same for me
